import type { Metadata } from "next";
import "./globals.css";
import { Navigation } from "@blocks/navigation";
import { AppProvider } from "@providers/AppProvider";
import { Fixel } from "@fonts/FixelDisplay";
import { cn } from "@helpers/ui/cn";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(Fixel.className, Fixel.variable)}>
        <AppProvider>
          <Navigation />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
